### ISSUE TITLE
Support the use of api tokens within rubrik calls

### ISSUE THREAD

**Issue by briandoodyie** [rubrikinc/rubrik-modules-for-ansible#38]
Currently we want a way to identify users who are running ansible calls to do rubrik snapshots. However the only way is for a user to locally store ldap login details (either in vault or as environments variables).

Please add an alternative way to supply credentials that is based on an api token that we have created ourselves through the gui

Calls to the module will contain a variable that can be set to the api_token. ```rubrik_api_token: xxxxxxxxxxxxxxx```

**Comment by drew-russell** [comment]
@briandoodyie we just released a new version of our Python SDK, which is what our Ansible modules consume, that includes support for API Token authentication. I'll be working on adding this functionality to the modules next.

**Comment by drew-russell** [comment]
@briandoodyie you'll now be able to supply an `api_token`, along with the `node_ip`, for authentication. We will also check your environment variables for `rubrik_cdm_token`.

The Quick Start guide has been updated with the full details as well: https://github.com/rubrikinc/rubrik-modules-for-ansible/blob/master/docs/quick-start.md
