### ISSUE TITLE
Add AHV support in sla assignment

### ISSUE THREAD

**Issue by danielharenkamp** [rubrikinc/rubrik-modules-for-ansible#59]
Actually there is only the possibility to add vmware vms, mssql hosts and volume groups to an sla domain.

There should be also support for adding ahv vms to an sla domain.
In module rubrik_on_demand_snapshot there is already an ahv integration so it should be possible to add support at sla assignment too.

Should be just an object_type: ahv

Regards
Daniel

**Comment by rfitzhugh** [comment]
@drew-russell is this issue resolved by PR #154?
