### ISSUE TITLE
quick start guide doesn't load

### ISSUE THREAD

**Issue by gnosis20** [rubrikinc/rubrik-modules-for-ansible#69]
**Expected Behavior**

Please describe the behavior you are expecting.

**Current Behavior**

What is the current behavior?

**Failure Information (for bugs)**

Please help provide information about the failure if this is a bug.

* Use verbose outputs to capture any debug information.
```
Paste into a code block.
```

**Steps to Reproduce**

Please provide detailed steps for reproducing the issue.

* Use numbered list.

**Context**

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Version of project.
* Version of dependencies.
* Version of operating system.

**Failure Logs**

Please include any relevant log snippets or files here.

* Use verbose outputs to capture any debug information.

```
Paste into a code block.
```

**Comment by drew-russell** [comment]
@gnosis20 thanks for catching. 

This has been fixed. 

Here is the direct link as well if needed: https://github.com/rubrikinc/rubrik-modules-for-ansible/blob/master/rubrikinc/cdm/docs/README.md
