### ISSUE TITLE
Add module to trigger a refresh of vCenter metadata

### ISSUE THREAD

**Issue by shamsway** [rubrikinc/rubrik-modules-for-ansible#83]
**Is your feature request related to a problem? Please describe.**

Refreshing vCenter metadata happens automatically on a regular basis, but it may be necessary to trigger a refresh to protect a newly deployed VM.

**Describe the solution you'd like**

Add a module to refresh the metadata for the specified vCenter Server, rubrik_refresh_vcenter

**Describe alternatives you've considered**

none

**Additional context**

n/a

**Comment by PaulVerhoeven1** [comment]
@shamsway i think this issue can be closed? feature is already implemented in the meantime.
