### ISSUE TITLE
Add a server to an organization

### ISSUE THREAD

**Issue by FrankMauroJr** [rubrikinc/rubrik-modules-for-ansible#94]
**Describe the solution you'd like**

I would like to be able to using ansible to add a server to an organization including "Availability Group"

Currently I log into the GUI and upgrade the organizations

**Describe alternatives you've considered**

n/a
**Additional context**

n/a

**Comment by drew-russell** [comment]
@FrankMauroJr which specific Protectable Object type (i.e vSphere VMs, Windows Hosts, etc) are you assigning to the organization?

I'm assuming that since you mentioned Availability Groups you are referring to SQL Server DBs but figured I'd double check

**Comment by FrankMauroJr** [comment]
Correct.

There would be two parts. One for native SQL backups and one with AOAG SQL backups (availability on).

Frank

**Comment by shamsway** [comment]
Resolved by #97

**Comment by FrankMauroJr** [comment]
I see the ticket was closed but I am not sure how I would ansible to assign a server to an organization.

I am the website “https://rubrik.gitbook.io/rubrik-modules-for-ansible/” but I do not see new modules.

What am I supposed to do.

Frank

**Comment by drew-russell** [comment]
@FrankMauroJr The new modules are still in the process of being published. I'll send out an update here later today for you.

**Comment by drew-russell** [comment]
@FrankMauroJr 

v1.0.6 of the Ansible Modules has been released. It includes the following new modules:

* rubrik_add_organization_protectable_object_mssql_server_host
* rubrik_add_organization_protectable_object_sql_server_availability_group
* rubrik_add_organization_protectable_object_sql_server_db

You'll need to be on the latest version of the Rubrik Python SDK as well.

**Comment by FrankMauroJr** [comment]
I downloaded the new modules to my machine.

I go to this site “https://rubrik.gitbook.io/rubrik-modules-for-ansible/” to get information on the modules but it does not contain the new modules. Is there another site I should be going to?

Thanks,
Frank

**Comment by FrankMauroJr** [comment]
I am trying to add a server to the organization. First part is to add the server to “Windows Hosts” just to the “Window Hosts” and “Target Window Hosts”; then I am adding to “SQL Server DBs” just “Hosts”

Which “module” am I supposed to be using for each. What am I doing wrong.

    - name: Rubrik assign policy to SQL part2
      rubrik_add_organization_protectable_object_mssql_server_host:
        provider: "{{ credentials }}"
        organization_name: gds-hs-dba-hosting
        mssql_host: VMKIT-CDCIEP01
TASK [Rubrik assign policy to SQL part2] **********************************************************************
fatal: [10.180.49.45]: FAILED! => {"changed": false, "msg": "Connect instance has no attribute 'add_organization_protectable_object_mssql_server_host'"}

PLAY RECAP ****************************************************************************************************
10.180.49.45               : ok=3    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
Is mssql_host supposed to be the SQL name? I just want to add a server.

    - name: Rubrik assign policy to SQL part1
      rubrik_add_organization_protectable_object_sql_server_db:
        provider: "{{ credentials }}"
        organization_name: gds-hs-dba-hosting
        mssql_host: VMKIT-CDCIEP01

TASK [Rubrik assign policy to SQL part1] ******************************************************************
fatal: [10.180.49.45]: FAILED! => {"changed": false, "msg": "missing required arguments: mssql_db, mssql_instance"}

PLAY RECAP ************************************************************************************************
10.180.49.45               : ok=3    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
Again, I just want to add a server not a specific mssql_db or mssql_instance.

Frank
(603)944-3337


From: Mauro Jr, Francesco
Sent: Monday, July 27, 2020 12:56 PM
To: rubrikinc/rubrik-modules-for-ansible <reply@reply.github.com>; rubrikinc/rubrik-modules-for-ansible <rubrik-modules-for-ansible@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: {EXTERNAL} Re: [rubrikinc/rubrik-modules-for-ansible] Add a server to an organization (#94)

I downloaded the new modules to my machine.

I go to this site “https://rubrik.gitbook.io/rubrik-modules-for-ansible/” to get information on the modules but it does not contain the new modules. Is there another site I should be going to?

Thanks,
Frank

**Comment by drew-russell** [comment]
@FrankMauroJr if you're just trying to add a server you can use the `rubrik_add_organization_protectable_object_mssql_server_host` module

Also, thanks for patience in the response here. I have been out of the office for the last two weeks.

**Comment by FrankMauroJr** [comment]
I am running the following playbook and am getting an error:
---
- hosts: "{{ hosts| default('rubrik_kdc')}}"
  connection: local
  gather_facts: false
  vars:
    credentials:
      api_token: "Basic YWRtaW46WGF2U3BlSnVsQ2hhRnJhMTIzNDU="
      node_ip: 10.180.49.45

  tasks:
    - name: get Rubrik
      debug:
        msg: "{{ credentials }}"
    - name: Rubrik Cluster Version
      rubrik_cluster_version:
        provider: "{{ credentials }}"
      register: version_info
    - name: show version
      debug:
        var: version_info.version
    - name: Rubrik assign policy to SQL part2
      rubrik_add_organization_protectable_object_mssql_server_host:
        provider: "{{ credentials }}"
        organization_name: "gds-CM_DBA_ADM"
        mssql_host: "VMKIT-CDCIEP01"


Output for running the playbook
# ansible-playbook ./rubrik.kdc.nonprod.test.yml -i host

PLAY [rubrik_kdc] *****************************************************************************************

TASK [get Rubrik] *****************************************************************************************
ok: [10.180.49.45] => {
    "msg": {
        "api_token": "Basic YWRtaW46WGF2U3BlSnVsQ2hhRnJhMTIzNDU=",
        "node_ip": "10.180.49.45"
    }
}

TASK [Rubrik Cluster Version] *****************************************************************************
[WARNING]: Platform linux on host 10.180.49.45 is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

ok: [10.180.49.45]

TASK [show version] ***************************************************************************************
ok: [10.180.49.45] => {
    "version_info.version": "5.1.0-p1-7918"
}

TASK [Rubrik assign policy to SQL part2] ******************************************************************
fatal: [10.180.49.45]: FAILED! => {"changed": false, "msg": "Connect instance has no attribute 'add_organization_protectable_object_mssql_server_host'"}

PLAY RECAP ************************************************************************************************
10.180.49.45               : ok=3    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by FrankMauroJr** [comment]
Is there anyway to talk to someone to help me resolve this problem?

Frank

From: Mauro Jr, Francesco
Sent: Tuesday, August 18, 2020 11:48 AM
To: rubrikinc/rubrik-modules-for-ansible <reply@reply.github.com>; rubrikinc/rubrik-modules-for-ansible <rubrik-modules-for-ansible@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: {EXTERNAL} Re: [rubrikinc/rubrik-modules-for-ansible] Add a server to an organization (#94)

I am running the following playbook and am getting an error:
---
- hosts: "{{ hosts| default('rubrik_kdc')}}"
  connection: local
  gather_facts: false
  vars:
    credentials:
      api_token: "Basic YWRtaW46WGF2U3BlSnVsQ2hhRnJhMTIzNDU="
      node_ip: 10.180.49.45

  tasks:
    - name: get Rubrik
      debug:
        msg: "{{ credentials }}"
    - name: Rubrik Cluster Version
      rubrik_cluster_version:
        provider: "{{ credentials }}"
      register: version_info
    - name: show version
      debug:
        var: version_info.version
    - name: Rubrik assign policy to SQL part2
      rubrik_add_organization_protectable_object_mssql_server_host:
        provider: "{{ credentials }}"
        organization_name: "gds-CM_DBA_ADM"
        mssql_host: "VMKIT-CDCIEP01"


Output for running the playbook
# ansible-playbook ./rubrik.kdc.nonprod.test.yml -i host

PLAY [rubrik_kdc] *****************************************************************************************

TASK [get Rubrik] *****************************************************************************************
ok: [10.180.49.45] => {
    "msg": {
        "api_token": "Basic YWRtaW46WGF2U3BlSnVsQ2hhRnJhMTIzNDU=",
        "node_ip": "10.180.49.45"
    }
}

TASK [Rubrik Cluster Version] *****************************************************************************
[WARNING]: Platform linux on host 10.180.49.45 is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

ok: [10.180.49.45]

TASK [show version] ***************************************************************************************
ok: [10.180.49.45] => {
    "version_info.version": "5.1.0-p1-7918"
}

TASK [Rubrik assign policy to SQL part2] ******************************************************************
fatal: [10.180.49.45]: FAILED! => {"changed": false, "msg": "Connect instance has no attribute 'add_organization_protectable_object_mssql_server_host'"}

PLAY RECAP ************************************************************************************************
10.180.49.45               : ok=3    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
